server:
  context-path: /api/limits

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/cmygehm_db?currentSchema=homework_8
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.default_schema: homework_8
    show-sql: true
    hibernate.ddl-auto: none
    open-in-view: false
  flyway:
    url: jdbc:postgresql://localhost:5435/cmygehm_db
    user: postgres
    password: postgres
    enabled: true
    locations: classpath:db/migration
    schemas: homework_8
    baseline-on-migrate: true

logging.level:
  org.flywaydb: DEBUG

settings:
  default-limit: 10000
  reset-schedule: "0 0 0 * * ?"
  transaction-check-schedule: "* * * * * ?"
  transaction-commit-waiting-time: "60s"